#!/bin/zsh

if [ "${1}" = "open" -o "${1}" = "o" ] ;then
   /Applications/EasyConnect.app/Contents/Resources/bin/EasyMonitor > /dev/null 2>&1 &
   /Applications/EasyConnect.app/Contents/MacOS/EasyConnect > /dev/null 2>&1 &

   echo "processes launched."
elif [ "${1}" = "kill" -o "${1}" = "k" -o "${1}" = "close" -o "${1}" = "c" ]; then 
   pkill EasyMonitor
   pkill ECAgent
   pkill ECAgentProxy

   echo "processes killed."
fi